### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by defunctzombie** [defunctzombie/polyfill-middleware#2]
Cache files in memory.

Not sure at what layer to cache yet. Possibly at the final bundle (we can actually precompute those on startup). Or just each file.

**Comment by jonathanong** [comment]
i think each polyfill should remain in memory (if polyfill becomes a lib and we `require()` it, it will be anyways), then do a LRU cache on `(useragent) -> bundle.js`

**Comment by defunctzombie** [comment]
I agree. This can be an option when initializing the middleware. I left an
options object in there for things like this.
