### ISSUE TITLE
compress

### ISSUE THREAD

**Issue by defunctzombie** [defunctzombie/polyfill-middleware#3]
need an option to compress the final js output

**Comment by jonathanong** [comment]
i'm guessing we're talking about uglifyjs. since we want this to be fast and not dependent on nginx, we may want to cache the gzipped/deflated values as well.

**Comment by defunctzombie** [comment]
Gzipped maybe. I am typically against gzip stuff in node. Wish there was a
better way to not build it into every middleware.

I am not against nginx for the proxy, that is up to end user. I run behind
nginx.

**Comment by jonathanong** [comment]
i just don't think you can assume everyone is running a reverse proxy server, but it's an over-optimization anyways.
